/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.bongole.ti.ga;

import java.lang.Thread.UncaughtExceptionHandler;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.google.analytics.tracking.android.ExceptionReporter;
import com.google.analytics.tracking.android.GAServiceManager;
import com.google.analytics.tracking.android.GoogleAnalytics;
import com.google.analytics.tracking.android.ServiceManager;
import com.google.analytics.tracking.android.Tracker;


@Kroll.module(name="GoogleAnalyticsAndroid", id="com.bongole.ti.ga")
public class GoogleAnalyticsAndroid extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "GoogleAnalyticsAndroidModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public GoogleAnalyticsAndroid()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public void start(KrollDict dict)
	{
		GoogleAnalytics ga = GoogleAnalytics.getInstance(TiApplication.getInstance().getApplicationContext());
		
		ga.setDebug(dict.getBoolean("debug"));
		
		Integer period = dict.getInt("dispatchInterval");
		GAServiceManager.getInstance().setDispatchPeriod( period == null ? 20 : period.intValue());
		
		Tracker tracker = ga.getTracker(dict.getString("account"));
		tracker.setAnonymizeIp(dict.getBoolean("anonymizeIp"));
		Double sampleRate = dict.getDouble("sampleRate");
		tracker.setSampleRate( sampleRate == null ? 100 : sampleRate.doubleValue());
		ga.setDefaultTracker(tracker);
		
		UncaughtExceptionHandler myHandler = new ExceptionReporter(
			    tracker,                                        // Currently used Tracker.
			    GAServiceManager.getInstance(),
			    Thread.getDefaultUncaughtExceptionHandler());     // Current default uncaught exception handler.

		Thread.setDefaultUncaughtExceptionHandler(myHandler); // Make myHandler the new default uncaught exception handler.
	}
	
	@Kroll.method
	public void trackView(KrollDict dict)
	{
		GoogleAnalytics ga = GoogleAnalytics.getInstance(TiApplication.getInstance().getApplicationContext());
		Tracker tracker = ga.getDefaultTracker();
		tracker.trackView(dict.getString("viewName"));
	}
	
	@Kroll.method
	public void trackEvent(KrollDict dict)
	{
		GoogleAnalytics ga = GoogleAnalytics.getInstance(TiApplication.getInstance().getApplicationContext());
		Tracker tracker = ga.getDefaultTracker();
		
		Integer value = dict.getInt("value");
		Long l = value == null ? null : new Long(value);
		tracker.trackEvent(dict.getString("category"), dict.getString("action"), dict.getString("label"), l);
	}
	
	@Kroll.method
	public void trackTiming(KrollDict dict)
	{
		GoogleAnalytics ga = GoogleAnalytics.getInstance(TiApplication.getInstance().getApplicationContext());
		Tracker tracker = ga.getDefaultTracker();
		
		Integer value = dict.getInt("value");
		Long l = value == null ? null : new Long(value);
		tracker.trackTiming(dict.getString("category"), l, dict.getString("name"), dict.getString("label"));
	}
	
	@Kroll.method
	public void startSession()
	{
		GoogleAnalytics ga = GoogleAnalytics.getInstance(TiApplication.getInstance().getApplicationContext());
		Tracker tracker = ga.getDefaultTracker();
		tracker.setStartSession(true);
	}
	
	@Kroll.method
	public void stoptSession()
	{
		GoogleAnalytics ga = GoogleAnalytics.getInstance(TiApplication.getInstance().getApplicationContext());
		Tracker tracker = ga.getDefaultTracker();
		tracker.setStartSession(false);
	}
}

